src/controllers/general_controller.py
from flask import Flask, Blueprint, render_template, request, redirect, url_for, session, flash
import jwt
from datetime import datetime
import sys

import database.users_db_manager as users_db
import database.character_db_manager as character_db
from helpers import create_jwt, send_email, login_required
from models.user import User
from settings import MAIL_DEFAULT_SENDER, SECRET_KEY

general_blueprint = Blueprint("general", __name__)


@general_blueprint.route("/")
@general_blueprint.route("/home")
def home():
    return render_template("home.html")


@general_blueprint.route("/login", methods=["POST", "GET"])
def login():
    session.clear()
    session.permanent = True

    if request.method == "GET":
        return render_template("login.html")

    # Reached by POST
    username = request.form["username"]

    user = users_db.get_user_by_username(request.form["username"])

    if user is None:
        flash("The username you have entered does not exist, please try again.", "warning")
        return render_template("login.html")

    if user.password != request.form["password"]:
        flash("You have entered the wrong password, please try again.", "warning")
        return render_template("login.html")

    session["username"] = username

    return redirect("/")


@general_blueprint.route("/users/<username>/profile")
def profile(username):
    user_info = users_db.get_user_by_username(username)
    return render_template("profile.html", user_info=user_info)


@general_blueprint.route("/signup", methods=["GET", "POST"])
def signup():
    if request.method == "GET":
        return render_template("signup.html")

    # Reached by POST

    username_signup = users_db.get_user_by_username(request.form["username"])
    if username_signup:
        flash("The username you have entered already exist, please enter another username.", "warning")
        return render_template("signup.html")

    # check if all information are provided
    if request.form["username"] is None:
        flash("You need to add the username", "warning")
        return render_template("signup.html")

    user = User(request.form["username"], request.form["name"], request.form["lastname"],
                request.form["email"], request.form["password"])
    users_db.add_user(user)

    token = create_jwt({'email': user.email, 'username': user.username}, SECRET_KEY)
    text = render_template('confirmation_email.html', username=user.username, token=token)

    send_email('Account Confirmation', MAIL_DEFAULT_SENDER, [user.email], text)

    flash("A confirmation email has been sent, please check your inbox.", "info")
    return redirect("/login")


@general_blueprint.route('/confirmregister/<token>')
def confirm_register(token):
    try:
        token = jwt.decode(token, SECRET_KEY, algorithms=['HS256'])
    except Exception as e:
        sys.stderr.write(str(e))
        token = 0
    if not token:
        flash("Email verification link invalid", "warning")
        return redirect("/register")

    user = users_db.get_user_by_username(token['username'])

    if datetime.strptime(token["expiration"], "%Y-%m-%dT%H:%M:%S.%f") < datetime.utcnow():
        users_db.delete_user(user)
        flash("Email verification link expired. Please register again using the same email.", "warning")
        return redirect("/register")

    user.verified = True
    users_db.update_user(user)

    return redirect("/login")


@general_blueprint.route("/choose-character", methods=["GET", "POST"])
@login_required
def choose_character():
    characters = character_db.get_all_characters()
    if request.method == "GET":
        session["character"] = "Evil Math Professor"
        return render_template("choose_character.html", characters=characters)

    session["character"] = request.form["character"]
    return redirect("/matches/quick")

src/templates/choose_character.html
{% extends "layout.html" %}

{% block title %}Choose Character{% endblock %}
{% block active %}Choose Your Character{% endblock %}

{% block main %}
<div class="text-center">
    <h1 class="text-center">Choose Your Character</h1>
    <b class="text-center">Scroll horizontally for more options</b>
</div>


<div style="display: flex; overflow: auto; white-space: nowrap">

    {% for character in characters: %}

    <form method="post">
        <button class="btn btn-primary" type="submit" value="{{character.name}}" name="character">
            <img src="/static/images/{{ character.images_buckets_name }}" style="max-width: 200px; max-height: 200px">
            <br>
            <p>{{character.name}}</p>
        </button>
    </form>
    <br>
    {% endfor %}

</div>

{% endblock %}

src/templates/confirmation_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<p>
    Dear {{ username }},

    If you have recently registered for an account, click on the following link to confirm your registration:

    {{ url_for('general.confirm_register', token=token, _external=True) }}
</p>
</body>
</html>

src/templates/home.html
<!-- join game -->

<!-- quick match -->

<!-- login -->
<!-- signup -->
{% extends "layout.html" %}

{% block title %}Home{% endblock %}
{% block active %}Home{% endblock %}

{% block main %}


    

        <img src="/static/images/blob.svg" style="max-width: 200px; position: relative; left: 50%; transform: translateX(-50%)">

        <div class="text-center">
            <h1 class="text-center">LearnWars</h1>
            <b class="text-center">Welcome to LearnWars: The Ultimate Game-Based Learning Platform for STEM Subjects!</b>
        </div>

    
        <div class="container text-center p-4 m-4">
            <div class="row">
              <div class="col">
                <button class="btn btn-primary" onclick="window.location.href = '/login';">Login</button>
              </div>
              <div class="col">
                <button class="btn btn-success" onclick="window.location.href = '/signup';">Sign Up</button>
              </div>
              <div class="col">
                <button class="btn btn-danger" onclick="window.location.href = '/choose-character';">Quick Game</button>
              </div>
            </div>
          </div>
    

    <div class="container">
        <div class="row">
          <div class="col">
            <img src="static/images/Screen Shot 2023-08-08 at 1.17.00 AM.png" style="max-width: 100%; position: relative; left: 50%; transform: translateX(-50%)">
          </div>
          <div class="col">
            <h2>Embark on an epic educational adventure like never before!</h2>
            <p>LearnWars is a thrilling game that combines the excitement of gaming with the power of learning. Designed specifically for middle and high school students, this innovative platform revolutionizes the way you experience science, technology, engineering, and mathematics (STEM) subjects. Get ready to dive into a virtual world where knowledge is your weapon and curiosity is your guide!</p>
          </div>
        </div>
        </div>
      </div>

      <div class="container">
        <div class="row">
          <div class="col">
            <h2>Interactive Gameplay</h2>
            <p>Prepare to be captivated by our immersive and interactive gameplay. Put your knowledge to the test as you tackle hands-on challenges inspired by real-world scenarios. Build bridges using engineering principles, unlock the secrets of chemical reactions, dissect virtual organisms, or program a robot to overcome obstacles. The possibilities are endless, and the adventure never stops!
            </p>
          </div>
          <div class="col">
            <img src="static/images/Screen Shot 2023-08-08 at 1.18.38 AM.png" style="max-width: 100%; position: relative; left: 50%; transform: translateX(-50%)">
        </div>
        </div>
        </div>
      </div>

      <div class="container">
        <div class="row">
          <div class="col">
            <img src="static/images/Screen Shot 2023-08-08 at 1.18.45 AM.png" style="max-width: 100%; position: relative; left: 50%; transform: translateX(-50%)">
          </div>
          <div class="col">
            <h2>Connect and Compete</h2>
            <p>Learning is better when shared with friends! Connect with like-minded individuals and form a community of STEM enthusiasts. Collaborate, exchange ideas, and support each other as you navigate the LearnWars universe. Engage in friendly competitions and see who can conquer the most challenging STEM challenges. Fuel your passion for learning through healthy competition!
            </p>
          </div>
        </div>
        </div>
      </div>

<br>
<br>
      <div class="text-center">
        <b class="">Are you ready to conquer the world of STEM and become a true champion of knowledge? Let the LearnWars begin!
        </b>
  
          
      </div>
      
{% endblock %}

src/templates/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="theme-color" content="#6ffa6c">

        <link href="/static/styles/bootstrap.min.css" rel="stylesheet">
        <link href="/static/styles/style.css" rel="stylesheet">
        <link href="/static/ctfLogo.png" rel="icon">
       
        <style>
            .myDiv {
                background-color: slategray;
            }
        </style>
</head>

        <title>{% block title %}{% endblock %} | {{ CLUB_NAME }}</title>

        {% block preload %}{% endblock %}

    </head>
    <body>
       

        <main class="container">
            {% with msg = get_flashed_messages(with_categories=True) %}
                {% if msg %}
                    {% for category, message in msg %}
                        <div class="alert alert-{{ category }} alert-dismissible fade show"
                             role="alert">
                            {{ message }}
                            <button type="button"
                                    class="btn-close"
                                    data-bs-dismiss="alert"
                                    aria-label="Close"></button>
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
            {% block main %}{% endblock %}
        </main>
        <footer>
            <hr>
            <p class="text-center">
                &copy; 2022-2023, {{ CLUB_NAME }}.
                <a href="/terms">Terms of Service</a> -
                <a href="/privacy">Privacy Policy</a>
            </p>
        </footer>

        <script src="/assets/js/nav.js"></script>
        <script src="/assets/js/showdown.min.js"></script>
        <script src="/assets/js/purify.min.js"></script>
        <script src="/assets/js/convertMD.js"></script>
        {% block script %}{% endblock %}
        <script src="/assets/js/seeMore.js"></script>
        <script src="/assets/js/newPagination.js"></script>
        <script src="/assets/js/dateConvert.js"></script>
        <script src="/assets/js/bootstrap.bundle.min.js"></script>
    </body>
</html>

src/templates/login.html
{% extends "layout.html" %}

{% block title %}Login{% endblock %}
{% block active %}Log In{% endblock %}

{% block main %}
<h1 class="text-center">Log In</h1>
<form method="post" action="#">
    <input autofocus
           class="form-control mb-3"
           name="username"
           placeholder="Username"
           required>
    <input class="form-control mb-3"
           name="password"
           placeholder="Password"
           type="password"
           required>
    <button class="btn btn-primary" type="submit">Log In</button>
    <a href="/forgotpassword" class="btn btn-secondary white">Forgot Password</a>
    {% if USE_CAPTCHA %}
        <script src="https://hcaptcha.com/1/api.js" async defer></script>
        <hr>
        <div class="h-captcha" data-sitekey= {{ site_key }} ></div>
    {% endif %}
    {% if request.args.get('next') %}
        <input type="hidden" name="next" value="{{ request.args.get('next') }}">
    {% endif %}
</form>
{% endblock %}

src/templates/signup.html
{% extends "layout.html" %}

{% block title %}Sign Up{% endblock %}
{% block active %}Sign Up{% endblock %}

{% block main %}
<h1 class="text-center">Sign Up</h1>
<form method="post">
    <input autocomplete="off"
           autofocus class="form-control mb-3"
           name="username"
           placeholder="Username"
           required>
    <input autocomplete="off"
           autofocus class="form-control mb-3"
           name="name"
           placeholder="First Name"
           required>
    <input autocomplete="off"
           autofocus class="form-control mb-3"
           name="lastname"
           placeholder="Last Name"
           required>
    <input class="form-control mb-3"
           name="email"
           placeholder="Email Address"
           type="email"
           required>
    <input class="form-control mb-3"
           name="password"
           id="password"
           placeholder="Password"
           type="password"
           autocomplete="new-password"
           required>
    <input class="form-control mb-3"
           name="confirmation"
           id="confirmation"
           placeholder="Confirmation"
           type="password"
           autocomplete="new-password"
           required>
    <button class="btn btn-primary" type="submit">Register</button>
    {% if USE_CAPTCHA %}
        <script src="https://hcaptcha.com/1/api.js" async defer></script>
        <hr>
        <div class="h-captcha" data-sitekey= {{ site_key }} ></div>
    {% endif %}
</form>
<br>
<p style="margin-top: 8px;">
    Your username can only contain alphanumeric characters, dashes, and underscores.
    Your password must be at least 8 characters long. Although they are stored with industry-grade
    encryption and nobody can see them even if they gain access to the users database, we strongly
    recommend you not to use a password you use elsewhere.<br><br>
    You must provide a valid email account to register on our site. By registering, you acknowledge
    that you have read our <a href="/privacy">privacy policy</a> and agree to abide by our
    <a href="/terms">terms of service</a>.
</p>
{% endblock %}
{% block script %}
<script>
    const newPassword = document.getElementById("password");
    const confirmPassword = document.getElementById("confirmation");
    document.querySelector("form").addEventListener("submit", event => {
        if (newPassword.value != confirmPassword.value) {
            makeAlert("Passwords do not match");
            event.preventDefault();
        }
        if (newPassword.value.length < 8) {
            makeAlert("Password must be at least 8 characters");
            event.preventDefault();
        }
    });

    function makeAlert(message) {
        var tmp = document.createElement('div');
        tmp.innerHTML = `<div class="alert alert-danger alert-dismissible fade show" role="alert">
                             ${message}
                             <button type="button"
                                     class="btn-close"
                                     data-bs-dismiss="alert"
                                     aria-label="Close"></button>
                         </div>`;
        document.querySelector("main").prepend(tmp.firstChild);
    }
</script>
{% endblock %}